typography_spectrum: 0.8814291306644088
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.46772526187564034
  lightness: 0.5896217748930327
  saturation: 0.354286613997699
  rhythmicContrast: 0.12577098519384566
github: true
layout_spectrum: 0.6233167119709646
analytics:
  google: UA-111277687-1
  facebook: '689052707899684'
author:
  name: Ben-Adam Michael
  email: jhenesus@gmail.com
  url: 'http://ultra-jesus.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966c2c3d-0f27-4150-96a3-1c5a4227356c.png
name: Jesus Christ
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: SoundCloud
    url: 'https://soundcloud.com/officialsonofman'
    type: external
  - name: Shop
    url: 'https://6ixyclothingco.com/shop'
    type: external
  - name: The Omega Point
    url: 'http://smarturl.it/THEOMEGAPOINT'
    type: external
  - name: Biography
    id: 39a95f4a-93af-424e-a73f-16b3b588c8d4
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d19ea6be-ad65-496f-bb7e-f9bf466b0a7f.png
title: ''
content: []
description: Feel an array of many emotions through the spiritual voice of a son...
purpose:
  - type: external
    url: 'https://soundcloud.com/officialsonofman/infinite-sunshine'
    label: Listen to "Infinite Sunshine"
  - type: contact
    url: 'mailto:archthemic@gmail.com'
    label: Contact me
