typography_spectrum: 0.8814291306644088
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.46772526187564034
  lightness: 0.5896217748930327
  saturation: 0.354286613997699
  rhythmicContrast: 0.12577098519384566
github: true
layout_spectrum: 0.6233167119709646
analytics:
  google: UA-111277687-1
  facebook: '689052707899684'
author:
  name: Ben-Adam Michael
  email: jhenesus@gmail.com
  url: 'http://ultra-jesus.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966c2c3d-0f27-4150-96a3-1c5a4227356c.png
name: Jesus Christ
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: SoundCloud
    url: 'https://soundcloud.com/officialsonofman'
    type: external
  - name: Shop
    url: 'https://6ixyclothingco.com/shop'
    type: external
  - name: The Omega Point
    url: 'http://smarturl.it/THEOMEGAPOINT'
    type: external
  - name: Biography
    id: 39a95f4a-93af-424e-a73f-16b3b588c8d4
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d19ea6be-ad65-496f-bb7e-f9bf466b0a7f.png
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FHp0x-QbNXYw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHp0x-QbNXYw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FHp0x-QbNXYw%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Jesus Christ
          url: 'https://www.youtube.com/channel/UCD8iIFZ6KTQW1xEJUg7uVIA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - jesus
        - son of god
        - christ
        - jesus christ
        - new music
        - christian
        - christianity
        - christian music
        - ancient waves
        - ancient of days
        - the lord
        - the bible
        - the holy b...
      description: >-
        Official Website: https://ultra-jesus.com Donate to boost my career as
        an artist: https://smarturl.it/DONATEFORCHANGE Download my latest demo
        "1 Soul 2 Fish" for FREE: smarturl.it/1Soul2Fish-DL
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=Hp0x-QbNXYw&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=Hp0x-QbNXYw&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=Hp0x-QbNXYw&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=Hp0x-QbNXYw&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=Hp0x-QbNXYw&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=Hp0x-QbNXYw'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=Hp0x-QbNXYw
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=Hp0x-QbNXYw
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/Hp0x-QbNXYw'
      title: Jesus Christ - Ancient Waves
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Feel an array of many emotions through the spiritual voice of a son...
purpose:
  - type: external
    url: 'https://soundcloud.com/officialsonofman/infinite-sunshine'
    label: Listen to "Infinite Sunshine"
  - type: contact
    url: 'mailto:archthemic@gmail.com'
    label: Contact me
