typography_spectrum: 0.8814291306644088
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.46772526187564034
  lightness: 0.5896217748930327
  saturation: 0.354286613997699
  rhythmicContrast: 0.12577098519384566
github: true
layout_spectrum: 0.6233167119709646
analytics:
  google: UA-111277687-1
  facebook: '689052707899684'
author:
  name: Ben-Adam Michael
  email: jhenesus@gmail.com
  url: 'http://ultra-jesus.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966c2c3d-0f27-4150-96a3-1c5a4227356c.png
name: Jesus Christ
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Music
    id: 00e73a50-40ae-4888-8597-eb9f88fae001
    type: content
  - name: Biography
    id: 10872fbc-182c-46ab-a53a-405b2807e20d
    type: content
  - name: Shop
    url: 'https://6ixyclothingco.com/shop'
    type: external
  - name: Writing
    id: 1eb13e2d-6ff8-4c8a-810f-8ad6840a8aa4
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d19ea6be-ad65-496f-bb7e-f9bf466b0a7f.png
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F2fq_ROCPKSM%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D2fq_ROCPKSM&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F2fq_ROCPKSM%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=2fq_ROCPKSM'
      keywords:
        - video footage
        - video footage free
        - video footage hd
        - video footage for editing
        - video footage background
        - video footage of mars
        - video footage of space
        - foot...
      related: []
      author:
        - name: Video Footage Free HD
          url: 'https://www.youtube.com/channel/UCa9A1fMA_NoRw1T0ABfJxqw'
          avatar: {}
      '@context': 'http://schema.org'
      title: 4K Rendered Space Travel Video Footage Free
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=2fq_ROCPKSM&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=2fq_ROCPKSM&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=2fq_ROCPKSM&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=2fq_ROCPKSM&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=2fq_ROCPKSM&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=2fq_ROCPKSM'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=2fq_ROCPKSM
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=2fq_ROCPKSM
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      description: >-
        https://vk.com/footagefreehd Футажи HD и 4K / Бесплатное Видео для
        Монтажа Watch movies online Movies in English ready for you to search,
        explore and watch.
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Feel an array of many emotions through the spiritual voice of a son...
purpose:
  - type: external
    url: 'https://soundcloud.com/j-c-official/infinite-sunshine'
    label: Listen to "Infinite Sunshine"
  - type: external
    url: 'http://smarturl.it/1soul2fish-dl'
    label: Download The Entire Demo
